services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php
      args:
        LOCAL_UID: ${LOCAL_UID:-0}
        LOCAL_GID: ${LOCAL_GID:-0}
    env_file:
      - ./.env.local
    working_dir: /var/www/app
    restart: unless-stopped
    volumes:
      - .:/var/www/app
    hostname: php
    extra_hosts:
      - host.docker.internal:host-gateway
    user: www-data
    networks:
      - default
    depends_on:
      - db

  db:
    image: mariadb:11.4
    restart: unless-stopped
    env_file:
      - ./.env.local
    working_dir: /var/lib/mysql
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
